variable "target_node" {}
variable "template" {}
variable "bridge" {}
variable "vlan" {}
variable "harbors" {}
variable "oracles" {}
variable "servers" {}
variable "leafs" {}
variable "prefix" {}
variable "userctn" {}
variable "publkeyctn" {}
variable "privkeyctn" {}
variable "storage" {}

variable "area" {}
variable "size" {}
variable "clone" {}
variable "nameserver" {}
variable "cloudinit" {}
variable "name_cluster" {}
variable "port_cluster" {}
variable "proxy" {}
variable "docker_login" {}
variable "docker_password" {}
