all:
  children:
    cluster:
      children:
        harbors:
          hosts:
%{ for harbor in harbors ~}
            ${harbor.name}:
              ansible_host: ${prefix}.${harbor.octet}
              ansible_name: ${harbor.name}
%{ endfor ~}
        servers:
          hosts:
%{ for server in servers ~}
            ${server.name}:
              ansible_host: ${prefix}.${server.octet}
              ansible_name: ${server.name}
              nats_port: ${server.natsport}
              leaf_port: ${server.leafport}
              cluster_port: ${server.clusterport}
              registry: ${prefix}.${server.octetregistry}
              label: ${server.label}
              wadm_enabled: ${server.wadm}
              master_enabled: ${server.master}
%{ endfor ~}
        leafs:
          hosts:
%{ for leaf in leafs ~}
            ${leaf.name}:
              ansible_host: ${prefix}.${leaf.octet}
              ansible_name: ${leaf.name}
              nats_port: ${leaf.natsport}
              host_port: ${prefix}.${leaf.octetattach}
              port_attach: ${leaf.portattach}
              registry: ${prefix}.${leaf.octetregistry}
              label: ${leaf.label}
%{ endfor ~}

  vars:
    ansible_user: ${userctn}
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ${privkeyctn}
