---
- name: install Harbor
  hosts: harbors
  become: true
  serial: 1
  vars:
    prefix: ${prefix}
    name_cluster: ${name_cluster}
    port_cluster: ${port_cluster}
    area: ${area}
    http_proxy: "${proxy}"
    https_proxy: "${proxy}"
    no_proxy: "${noproxy}"

  environment:
    http_proxy: "${proxy}"
    https_proxy: "${proxy}"
    no_proxy: "${noproxy}"

  roles:
    - harbor
