---
- name: install Nats on servers
  hosts: servers
  become: true
  serial: 1

  vars:
    prefix: 192.188.10
    oracle: 192.188.10.110
    name_cluster: wasmcloud
    port_cluster: 6222
    area: south
    http_proxy: ""
    https_proxy: ""
    no_proxy: "127.0.0.1,localhost"

  environment:
    http_proxy: ""
    https_proxy: ""
    no_proxy: "127.0.0.1,localhost"

  roles:
    - nats

- name: install Nats on servers
  hosts: leafs
  become: true
  serial: 1

  vars:
    prefix: 192.188.10
    oracle: 192.188.10.110
    name_cluster: wasmcloud
    port_cluster: 6222
    area: south
    http_proxy: ""
    https_proxy: ""
    no_proxy: "127.0.0.1,localhost"

  environment:
    http_proxy: ""
    https_proxy: ""
    no_proxy: "127.0.0.1,localhost"

  roles:
    - nats
